"""add rekoendasi

Revision ID: 5cddeed6a17b
Revises: 6ea2bbf0dc01
Create Date: 2025-02-26 01:03:18.029517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cddeed6a17b'
down_revision = '6ea2bbf0dc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rekomendasi', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.drop_column('rekomendasi')

    # ### end Alembic commands ###
