"""update rekoendasi

Revision ID: 6ea2bbf0dc01
Revises: a4a40feab53b
Create Date: 2025-02-26 01:02:32.939809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ea2bbf0dc01'
down_revision = 'a4a40feab53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.drop_column('rekomendasi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rekomendasi', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
