"""edit datasiswa

Revision ID: 939305757e4c
Revises: 2e657a6c5c25
Create Date: 2025-02-21 00:27:15.751779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939305757e4c'
down_revision = '2e657a6c5c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=False),
    sa.Column('alamat_sekolah', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('datasiswa')
    # ### end Alembic commands ###
