"""update relasi

Revision ID: a4a40feab53b
Revises: cf87065c3540
Create Date: 2025-02-26 00:34:37.370616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a40feab53b'
down_revision = 'cf87065c3540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.drop_constraint('bakatsiswa_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasiswa', ['siswa_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakatsiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bakatsiswa_ibfk_1', 'datasiswa', ['siswa_id'], ['id'])

    # ### end Alembic commands ###
