"""add bakatsiswa table

Revision ID: cf87065c3540
Revises: 939305757e4c
Create Date: 2025-02-26 00:08:11.722774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf87065c3540'
down_revision = '939305757e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakatsiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('jurusan', sa.String(length=100), nullable=False),
    sa.Column('deskripsi_bakat', sa.Text(), nullable=False),
    sa.Column('rekomendasi', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['datasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bakatsiswa')
    # ### end Alembic commands ###
